server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/to_dolist
    username: root
    password: Password
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: "qa"

  jpa:
    hibernate:
      ddl-auto: update   # use 'create', 'validate', or 'none' as needed
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  config:
    import: "optional:configserver:http://localhost:8071/"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
eureka:
  instance:
    preferIpaddress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka

info:
  app: "Bank application"
  developer: "Bhaskar Gomasu"
  from : "Thimmampet-Waragal Telangana"




